# Generated by Django 3.2.9 on 2021-11-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='img/users'),
        ),
    ]
