# Generated by Django 3.2.9 on 2021-11-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
        ('orders', '0004_auto_20211129_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpoduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderpoduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
