# Generated by Django 3.2.9 on 2021-11-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, unique=True)),
                ('cat_slug', models.CharField(max_length=150, unique=True)),
                ('cat_desc', models.TextField(blank=True, max_length=500)),
                ('cat_img', models.ImageField(blank=True, upload_to='img/cat')),
            ],
            options={
                'verbose_name': 'cat',
                'verbose_name_plural': 'cat',
            },
        ),
    ]
