# Generated by Django 3.2.9 on 2021-11-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
