# Generated by Django 3.2.9 on 2021-11-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cat', '0002_alter_cat_cat_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, unique=True)),
                ('product_slug', models.SlugField(max_length=500, unique=True)),
                ('product_desc', models.TextField(blank=True, max_length=500)),
                ('product_price', models.ImageField(upload_to='')),
                ('product_img', models.ImageField(blank=True, upload_to='img/product')),
                ('product_stock', models.ImageField(upload_to='')),
                ('product_is_available', models.BooleanField(default=True)),
                ('product_created_date', models.DateTimeField(auto_now_add=True)),
                ('product_modified_date', models.DateTimeField(auto_now=True)),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.cat')),
            ],
        ),
    ]
