# Generated by Django 3.2.9 on 2021-11-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='busket',
            new_name='buskett',
        ),
    ]
